import{a as v,S as P,i}from"./assets/vendor-Do60_h77.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const S="55463829-87ababc408fcd8cb97ff0a765",q=15;async function y(a,t=1){return(await v.get("https://pixabay.com/api/",{params:{key:S,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:q,page:t}})).data}const l=document.querySelector(".gallery"),u=document.querySelector(".loader"),f=document.querySelector(".load-btn");let R=new P(".gallery a",{captionsData:"alt",captionDelay:250});function h(a){if(!l)return;const t=a.map(o=>`
        <li class="gallery-item">
        <a class="item-link" href="${o.largeImageURL}">
            <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="img-info-wrapper">
            <p class="img-info">Likes: <span class="info-accent">${o.likes}</span></p>
            <p class="img-info">Views: <span class="info-accent">${o.views}</span></p>
            <p class="img-info">Comments: <span class="info-accent">${o.comments}</span></p>
            <p class="img-info">Downloads: <span class="info-accent">${o.downloads}</span></p>
        </div>
        </li>
    `).join("");l.insertAdjacentHTML("beforeend",t),R.refresh()}function M(){l&&(l.innerHTML="")}function w(){u&&u.classList.add("active")}function L(){u&&u.classList.remove("active")}function E(a){return new Promise(t=>setTimeout(t,a))}function b(){f&&f.classList.add("is-visible")}function c(){f&&f.classList.remove("is-visible")}const p=document.querySelector(".form"),$=document.querySelector(".load-btn");let n=1,m="",g=0;if(p){p.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements["search-text"].value.trim();if(!o){i.warning({title:"Caution",message:"Please enter a search query!",position:"topRight"});return}m=o,n=1,M(),c(),w();try{const s=await y(m,n);if(g=s.totalHits,await E(500),s.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(s.hits);const e=Math.ceil(g/PER_PAGE);n<e?b():(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),p.reset()}});async function a(){n+=1,c(),w();try{const t=await y(m,n);h(t.hits);const o=Math.ceil(g/15);n<o?b():(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const s=document.querySelector(".gallery-item");if(s){const e=s.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}$.addEventListener("click",a)}
//# sourceMappingURL=index.js.map
